from __future__ import annotations

import json
import os
import uuid
from pathlib import Path

import pytest

from scripts.incremental_migration.database import (
    apply_database_merge,
    copy_table_to_gzip,
    create_and_load_staging,
    drop_migration_schema,
    preflight_database_merge,
    read_database_marker,
    rollback_database_merge,
    staging_schema_name,
    verify_loaded_staging,
)
from scripts.incremental_migration.domain import MigrationWindow
from scripts.incremental_migration.manifest import BaselineManifest, ExportManifest
from scripts.incremental_migration.policy import TableRole
from scripts.incremental_migration.postgres import fingerprint_table, read_database_catalog
from scripts.incremental_migration.service import (
    apply_import,
    dry_run_import,
    export_package,
    prepare_target_baseline,
    rollback_import,
    verify_import,
)


@pytest.fixture(scope="module")
def disposable_postgres_dsn() -> str:
    raw_dsn = os.getenv("DEER_FLOW_TEST_POSTGRES_DSN")
    if not raw_dsn:
        pytest.skip("set DEER_FLOW_TEST_POSTGRES_DSN to run PostgreSQL migration integration tests")

    import psycopg
    from psycopg import sql
    from psycopg.conninfo import make_conninfo

    try:
        bootstrap = psycopg.connect(raw_dsn, autocommit=True)
    except psycopg.Error:
        pytest.skip("DEER_FLOW_TEST_POSTGRES_DSN is not reachable")
    database_name = f"deerflow_migration_it_{uuid.uuid4().hex[:16]}"
    with bootstrap:
        with bootstrap.cursor() as cursor:
            cursor.execute("SELECT role_row.rolcreatedb OR role_row.rolsuper FROM pg_catalog.pg_roles role_row WHERE role_row.rolname = current_user")
            if not bool(cursor.fetchone()[0]):
                pytest.skip("DEER_FLOW_TEST_POSTGRES_DSN role cannot create an isolated test database")
            cursor.execute(sql.SQL("CREATE DATABASE {}").format(sql.Identifier(database_name)))
        test_dsn = make_conninfo(raw_dsn, dbname=database_name)
        try:
            yield test_dsn
        finally:
            with bootstrap.cursor() as cursor:
                cursor.execute(
                    "SELECT pg_catalog.pg_terminate_backend(pid) FROM pg_catalog.pg_stat_activity WHERE datname = %s AND pid <> pg_catalog.pg_backend_pid()",
                    (database_name,),
                )
                cursor.execute(sql.SQL("DROP DATABASE {}").format(sql.Identifier(database_name)))


@pytest.fixture
def pg_connection(disposable_postgres_dsn: str):
    import psycopg

    with psycopg.connect(disposable_postgres_dsn) as connection:
        with connection.cursor() as cursor:
            cursor.execute("DROP SCHEMA public CASCADE")
            cursor.execute("CREATE SCHEMA public")
        connection.commit()
        yield connection
        connection.rollback()


def _create_users_table(connection) -> None:
    with connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE TABLE public.users (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email text NOT NULL UNIQUE,
                profile json NOT NULL,
                payload bytea,
                note text,
                created_at timestamptz NOT NULL
            )
            """
        )
    connection.commit()


def _manifest_for_users(*, catalog, payload, export_id: str) -> ExportManifest:
    return ExportManifest.create(
        baseline_id=export_id,
        source_environment="test-source",
        target_environment="test-target",
        window=MigrationWindow.parse("2026-07-13T00:00:00+08:00", "2026-07-20T00:00:00+08:00"),
        source_catalog=catalog,
        selected_thread_ids=(),
        owner_by_thread={},
        tables=(payload,),
        files=(),
        export_id=export_id,
    )


def test_postgres_copy_merge_sequence_and_logical_rollback(pg_connection, tmp_path: Path) -> None:
    _create_users_table(pg_connection)
    with pg_connection.cursor() as cursor:
        cursor.execute(
            """
            INSERT INTO public.users (id, email, profile, payload, note, created_at)
            OVERRIDING SYSTEM VALUE VALUES
              (10, 'first@example.test', '{"b":2,"a":1}', %s, %s, '2026-07-13T00:00:00Z'),
              (20, 'second@example.test', '{"nested":{"value":true}}', %s, %s, '2026-07-14T00:00:00Z')
            """,
            (b"source\x00bytes", "line one\nline two\\tail", b"second", "plain"),
        )
    pg_connection.commit()

    source_catalog = read_database_catalog(pg_connection)
    users = source_catalog.table_by_name["users"]
    source_fingerprint = fingerprint_table(pg_connection, users)
    output = tmp_path / "db/users.copy.gz"
    payload = copy_table_to_gzip(
        pg_connection,
        table=users,
        output_path=output,
        data_path="db/users.copy.gz",
        role=TableRole.GLOBAL,
        source_payload_hash=source_fingerprint.payload_hash,
    )
    manifest = _manifest_for_users(catalog=source_catalog, payload=payload, export_id="postgres-roundtrip")
    pg_connection.commit()

    with pg_connection.cursor() as cursor:
        cursor.execute("TRUNCATE public.users RESTART IDENTITY")
        cursor.execute(
            """
            INSERT INTO public.users (id, email, profile, payload, note, created_at)
            OVERRIDING SYSTEM VALUE VALUES
              (10, 'stale@example.test', '{"stale":true}', %s, 'old', '2026-07-01T00:00:00Z'),
              (30, 'target-only@example.test', '{}', %s, 'keep', '2026-07-01T00:00:00Z')
            """,
            (b"stale", b"target-only"),
        )
        cursor.execute("SELECT setval(pg_get_serial_sequence('public.users', 'id'), 7, true)")
    pg_connection.commit()

    target_catalog = read_database_catalog(pg_connection)
    schema = create_and_load_staging(
        pg_connection,
        package_root=tmp_path,
        manifest=manifest,
        target_catalog=target_catalog,
    )
    verify_loaded_staging(
        pg_connection,
        manifest=manifest,
        target_catalog=target_catalog,
        staging_schema=schema,
    )
    preview = preflight_database_merge(
        pg_connection,
        manifest=manifest,
        target_catalog=target_catalog,
        staging_schema=schema,
    )
    assert preview.tables[0].insert_count == 1
    assert preview.tables[0].update_count == 1
    assert preview.tables[0].target_only_count == 1

    applied = apply_database_merge(
        pg_connection,
        manifest=manifest,
        target_catalog=target_catalog,
        staging_schema=schema,
    )
    assert read_database_marker(pg_connection, staging_schema=schema).status == "db_committed"
    with pg_connection.cursor() as cursor:
        cursor.execute("SELECT id, email, payload, note FROM public.users ORDER BY id")
        rows = cursor.fetchall()
        cursor.execute("SELECT last_value, is_called FROM public.users_id_seq")
        sequence_after = cursor.fetchone()
    assert [row[0] for row in rows] == [10, 20, 30]
    assert rows[0][1:] == ("first@example.test", b"source\x00bytes", "line one\nline two\\tail")
    assert rows[2][1] == "target-only@example.test"
    assert sequence_after == (30, True)

    rollback_database_merge(
        pg_connection,
        manifest=manifest,
        target_catalog=target_catalog,
        staging_schema=schema,
        sequence_states=applied.sequence_states,
    )
    assert read_database_marker(pg_connection, staging_schema=schema).status == "rolled_back"
    with pg_connection.cursor() as cursor:
        cursor.execute("SELECT id, email, payload FROM public.users ORDER BY id")
        rolled_back_rows = cursor.fetchall()
        cursor.execute("SELECT last_value, is_called FROM public.users_id_seq")
        sequence_rolled_back = cursor.fetchone()
    assert rolled_back_rows == [
        (10, "stale@example.test", b"stale"),
        (30, "target-only@example.test", b"target-only"),
    ]
    assert sequence_rolled_back == (7, True)
    drop_migration_schema(pg_connection, schema, expected_export_id=manifest.export_id)
    pg_connection.commit()


def test_postgres_business_key_collision_blocks_apply(pg_connection, tmp_path: Path) -> None:
    _create_users_table(pg_connection)
    with pg_connection.cursor() as cursor:
        cursor.execute("INSERT INTO public.users (id, email, profile, created_at) OVERRIDING SYSTEM VALUE VALUES (1, 'same@example.test', '{}', '2026-07-13T00:00:00Z')")
    pg_connection.commit()
    catalog = read_database_catalog(pg_connection)
    fingerprint = fingerprint_table(pg_connection, catalog.table_by_name["users"])
    payload = copy_table_to_gzip(
        pg_connection,
        table=catalog.table_by_name["users"],
        output_path=tmp_path / "db/users.copy.gz",
        data_path="db/users.copy.gz",
        role=TableRole.GLOBAL,
        source_payload_hash=fingerprint.payload_hash,
    )
    manifest = _manifest_for_users(catalog=catalog, payload=payload, export_id="postgres-conflict")
    pg_connection.commit()
    with pg_connection.cursor() as cursor:
        cursor.execute("TRUNCATE public.users RESTART IDENTITY")
        cursor.execute("INSERT INTO public.users (id, email, profile, created_at) OVERRIDING SYSTEM VALUE VALUES (2, 'same@example.test', '{}', '2026-07-13T00:00:00Z')")
    pg_connection.commit()
    target_catalog = read_database_catalog(pg_connection)
    schema = create_and_load_staging(
        pg_connection,
        package_root=tmp_path,
        manifest=manifest,
        target_catalog=target_catalog,
    )

    report = preflight_database_merge(
        pg_connection,
        manifest=manifest,
        target_catalog=target_catalog,
        staging_schema=schema,
    )

    assert any(conflict.conflict_type.endswith("target_collision") for conflict in report.conflicts)
    with pytest.raises(ValueError, match="preflight found conflicts"):
        apply_database_merge(
            pg_connection,
            manifest=manifest,
            target_catalog=target_catalog,
            staging_schema=schema,
        )
    with pg_connection.cursor() as cursor:
        cursor.execute("SELECT id FROM public.users")
        assert cursor.fetchall() == [(2,)]
    pg_connection.rollback()


def test_postgres_catalog_is_search_path_stable_and_ignores_include_columns(pg_connection) -> None:
    with pg_connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE TABLE public.users (
                id text NOT NULL,
                email text NOT NULL,
                note text,
                PRIMARY KEY (id) INCLUDE (note),
                UNIQUE (email) INCLUDE (note)
            )
            """
        )
    pg_connection.commit()
    with pg_connection.cursor() as cursor:
        cursor.execute("SET search_path = public")
    pg_connection.commit()
    first = read_database_catalog(pg_connection)
    pg_connection.rollback()
    with pg_connection.cursor() as cursor:
        cursor.execute("SET search_path = pg_catalog")
    pg_connection.commit()
    second = read_database_catalog(pg_connection)

    assert first.structural_fingerprint == second.structural_fingerprint
    users = first.table_by_name["users"]
    assert users.primary_key == ("id",)
    assert any(not index.primary and index.columns == ("email",) for index in users.unique_indexes)
    pg_connection.rollback()


def test_postgres_fingerprints_unkeyed_bookkeeping_rows_stably(pg_connection) -> None:
    with pg_connection.cursor() as cursor:
        cursor.execute("CREATE TABLE public.alembic_version (version_num varchar(32) NOT NULL)")
        cursor.execute(
            "INSERT INTO public.alembic_version (version_num) VALUES (%s), (%s), (%s)",
            ("revision-b", "revision-a", "revision-a"),
        )
    pg_connection.commit()
    table = read_database_catalog(pg_connection).table_by_name["alembic_version"]

    first = fingerprint_table(pg_connection, table, allow_unkeyed=True)
    pg_connection.rollback()
    with pg_connection.cursor() as cursor:
        cursor.execute("TRUNCATE public.alembic_version")
        cursor.execute(
            "INSERT INTO public.alembic_version (version_num) VALUES (%s), (%s), (%s)",
            ("revision-a", "revision-a", "revision-b"),
        )
    pg_connection.commit()
    second = fingerprint_table(pg_connection, table, allow_unkeyed=True)

    assert table.primary_key == ()
    assert first == second
    assert first.row_count == 3
    with pytest.raises(ValueError, match="without a primary key"):
        fingerprint_table(pg_connection, table)
    pg_connection.rollback()


def test_service_workflow_export_apply_verify_and_rollback(pg_connection, tmp_path: Path) -> None:
    with pg_connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE TABLE public.users (
                id text PRIMARY KEY,
                email text NOT NULL UNIQUE,
                created_at timestamptz NOT NULL
            );
            CREATE TABLE public.threads_meta (
                thread_id text PRIMARY KEY,
                user_id text NOT NULL,
                title text,
                created_at timestamptz NOT NULL,
                updated_at timestamptz NOT NULL
            );
            CREATE TABLE public.runs (
                run_id text PRIMARY KEY,
                thread_id text NOT NULL,
                status text NOT NULL,
                created_at timestamptz NOT NULL,
                updated_at timestamptz NOT NULL
            );
            CREATE TABLE public.store (
                prefix text NOT NULL,
                key text NOT NULL,
                value jsonb NOT NULL,
                PRIMARY KEY (prefix, key)
            );
            CREATE TABLE public.alembic_version (version_num text NOT NULL);
            INSERT INTO public.alembic_version VALUES ('revision-1');
            INSERT INTO public.users VALUES ('u', 'before@example.test', '2026-07-01T00:00:00Z');
            INSERT INTO public.threads_meta VALUES (
                't', 'u', 'before', '2026-07-01T00:00:00Z', '2026-07-01T00:00:00Z'
            );
            INSERT INTO public.store VALUES (
                'threads', 't', '{"metadata":{"user_id":"u"}}'
            );
            """
        )
    pg_connection.commit()

    target_home = tmp_path / "target-home"
    target_file = target_home / "users/u/threads/t/user-data/workspace/note.txt"
    target_file.parent.mkdir(parents=True)
    target_file.write_text("before", encoding="utf-8")
    state_dir = tmp_path / "state"
    window = MigrationWindow.parse("2026-07-13T00:00:00+08:00", "2026-07-20T00:00:00+08:00")
    planned = prepare_target_baseline(
        pg_connection,
        target_home=target_home,
        state_dir=state_dir,
        environment="prod",
        window=window,
        source_environment="dev-deerflow",
        apply=True,
        confirm_services_stopped=True,
    )
    baseline_path = Path(planned.baseline_path or "")

    with pg_connection.cursor() as cursor:
        cursor.execute("UPDATE public.users SET email = 'source@example.test' WHERE id = 'u'")
        cursor.execute("UPDATE public.threads_meta SET title = 'source', updated_at = '2026-07-15T00:00:00Z' WHERE thread_id = 't'")
    pg_connection.commit()
    source_home = tmp_path / "source-home"
    source_file = source_home / "users/u/threads/t/user-data/workspace/note.txt"
    source_file.parent.mkdir(parents=True)
    source_file.write_text("source", encoding="utf-8")
    package_path = tmp_path / "migration.tar.gz"
    export_package(
        pg_connection,
        source_home=source_home,
        baseline=BaselineManifest.read(baseline_path),
        window=window,
        output_path=package_path,
        work_root=tmp_path / "export-work",
        source_environment="dev-deerflow",
        target_environment="prod",
        confirm_services_stopped=True,
    )

    with pg_connection.cursor() as cursor:
        cursor.execute("UPDATE public.users SET email = 'before@example.test' WHERE id = 'u'")
        cursor.execute("UPDATE public.threads_meta SET title = 'before', updated_at = '2026-07-01T00:00:00Z' WHERE thread_id = 't'")
    pg_connection.commit()

    preview = dry_run_import(
        pg_connection,
        package_path=package_path,
        target_home=target_home,
        state_dir=state_dir,
        work_root=tmp_path / "dry-run-work",
    )
    assert preview.applied is False
    applied = apply_import(
        pg_connection,
        package_path=package_path,
        target_home=target_home,
        state_dir=state_dir,
        confirm_services_stopped=True,
    )
    assert applied.applied is True
    state_value = json.loads((state_dir / "state.json").read_text(encoding="utf-8"))
    package_identity = state_value["details"]["package_identity"]
    marker = read_database_marker(pg_connection, staging_schema=staging_schema_name(planned.migration_id))
    assert marker.details["package_content_sha256"] == package_identity
    verified = verify_import(pg_connection, target_home=target_home, state_dir=state_dir)
    assert verified.verified is False
    with pg_connection.cursor() as cursor:
        cursor.execute("SELECT email FROM public.users WHERE id = 'u'")
        assert cursor.fetchone()[0] == "source@example.test"
    assert target_file.read_text(encoding="utf-8") == "source"

    rolled_back = rollback_import(
        pg_connection,
        target_home=target_home,
        state_dir=state_dir,
        confirm_services_stopped=True,
    )
    assert rolled_back.phase.value == "ROLLED_BACK"
    with pg_connection.cursor() as cursor:
        cursor.execute("SELECT email FROM public.users WHERE id = 'u'")
        assert cursor.fetchone()[0] == "before@example.test"
    assert target_file.read_text(encoding="utf-8") == "before"
